name: lint-and-test

on: push


jobs:
  check:
    runs-on: ubuntu-latest
    name: Check (on Python3.8)
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - uses: pre-commit/action@v2.0.0

  test:
    needs: check
    runs-on: ubuntu-latest
    #strategy:  # TODO: make work with pre-commit
    #  matrix:
    #    python-version: [ '3.8', '3.6' ]
    name: "Test (on Python3.8)"
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - run: pytest
