name: lint-and-test

on: push


jobs:
  check:
    runs-on: ubuntu-latest
    name: "Check (on Python3.10)"
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0

  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: "Test (on Python 3.10)"
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Check out src from Git
        uses: actions/checkout@v3
      - name: Get history and tags for SCM versioning to work
        run: |
          git fetch --prune --unshallow
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: make test
